### ISSUE TITLE
device description url? 

### ISSUE THREAD

**Issue by MrAvana** [StevenLooman/home-assistant-dlna-dmr#7]
How do I find the device description url for my TV?

**Comment by StevenLooman** [comment]
This component is now integrated into home assistant itself. You should use that instead. Netdisco/discovery will discover the device for you without any manual configuration.

Still, you still have to enable discovery of it explicitly. You can do this by opting-in discovery of dlna_dmr devices, like so in your config:
```
discovery:
  enable:
    - dlna_dmr
```

Otherwise, if you still want to know the device description URL for your TV, you can run netdisco manually, like so:
```
dlna_dmr:
[{'host': '192.168.1.14',
  'manufacturer': 'Samsung Electronics',
  'model_name': 'UE50KU6000',
  'model_number': 'AllShare1.0',
  'name': '[TV] Samsung 6 Series (50)',
  'port': 9197,
  'serial': '0CCS3HIHC00137H',
  'ssdp_description': 'http://192.168.1.14:9197/dmr',
  'udn': 'uuid:4d672690-9e27-4f2a-8426-3e8334427884',
  'upnp_device_type': 'urn:schemas-upnp-org:device:MediaRenderer:1'},
 {'host': '192.168.1.15',
  'manufacturer': 'JF Light Industries',
  'model_name': 'UpMPD',
  'model_number': '1.0',
  'name': 'MusicBox',
  'port': 49152,
  'serial': '42',
  'ssdp_description': 'http://192.168.1.15:49152/description.xml',
  'udn': 'uuid:e3a17dd5-9d85-3131-3c34-b827eb498d72',
  'upnp_device_type': 'urn:schemas-upnp-org:device:MediaRenderer:1'}]
```

ssdp_description shows the device description URL.

**Comment by mykola-dev** [comment]
@StevenLooman sorry for asking here, but:
Is it possible to use DMR device with random port?
I use foobar2000 player as my DMR on Windows. Each time i restart PC, foobar creates dmr service on random port. This mean i can use only auto discovery feature in the Hassio since `media_player` section requires exact port number.
```
media_player:
 - platform: dlna_dmr
   name: foobar
   url: http://192.168.1.100:?????
```
Unfortunately hassio auto discovery triggers only on start. It can't rescan devices during the work. So when i restart my pc it loses autodiscovered foobar's DMR

**Comment by StevenLooman** [comment]
Which DLNA component are you using for foobar2000? I see two at the
foobar2000 website.

**Comment by mykola-dev** [comment]
I use `foo_upnp`
https://www.foobar2000.org/components/view/foo_upnp
i thought this is the only one. Could you please share the link to another one?

I also would like to switch to any other DMR solution to play HA sounds on my windows pc. But so far foobar is the only appropriate way.

**Comment by StevenLooman** [comment]
Sorry for the late reply. On the `foobar2000` page I see these two:
- [UPnP MediaRenderer Output](https://www.foobar2000.org/components/view/foo_out_upnp)
- [UPnP/DLNA Renderer, Server, Control Point](https://www.foobar2000.org/components/view/foo_upnp)

Note that I have tested none of these! On the [documentation-page](http://bubbleguuum.free.fr/foo_upnp/foo_upnp.txt) of `foo_upnp` I see that you can also use port 80. You can try url `http://192.168.1.100:80/...` in your configuration.

However, Home Assistant should pick up newly advertised DMR normally. Unfortunately, I cannot reproduce it (as I have no application which provides DMR services on random ports.)

I am curious though. Can you enable UPnP/DLNA/discovery specific logging in home assistant by adding this to your configuration:
```
logger:
  default: info
  logs:
    homeassistant.components.media_player.dlna_dmr: debug
    homeassistant.components.discovery: debug
    async_upnp_client: debug
    async_upnp_client.dlna: debug
    async_upnp_client.traffic: info
```

This will silence Home Assistant for most this other than UPnP/DLNA and discovery. Please check if you see anything with regard to discovery and the like.

**Comment by mykola-dev** [comment]
Sorry. I have uninstalled foobar already. So cant check.
I switched to MPD for Windows. Works good so far.

**Comment by StevenLooman** [comment]
Ok. Note that Home Assistant has a MPD component as well. Also, MPD can be extended with a UPnP service.

**Comment by jyz0501** [comment]
I have a Hisense TV. The ADB service has been started and LOG debug has been configured. Here are my debug files.
This url address shows SCDPURL.

[home-assistant.log](https://github.com/StevenLooman/home-assistant-dlna-dmr/files/4310548/home-assistant.log)

**Comment by StevenLooman** [comment]
Please open a new issue. Also, please provide the problem.
